name: Greeting from Dai Zijie
on: push
jobs:
  my-job:
  name: My Job
  runs-on: ubuntu-18.04
  steps:
  - name: Print a greeting
    env:
       My_VAR: Hi there! My name is
       FIRST_NAME: Zijie
       LAST_NAME: Dai
    run:
     echo $MY_VAR $FIRST_NAME $LAST_NAME.
